version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    networks:
      - coffee_and_happiness_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coffee_and_happiness_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app_container
    networks:
      - coffee_and_happiness_network
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee_and_happiness_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: "docker"

networks:
  coffee_and_happiness_network:
    driver: bridge

volumes:
  mysql_data: