version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app_container
    networks:
      - coffee_and_happiness_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://coffee-and-happiness-serv.mysql.database.azure.com:3306/coffee_and_happiness?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&verifyServerCertificate=true
      SPRING_DATASOURCE_USERNAME: mdn
      SPRING_DATASOURCE_PASSWORD: P4ssw0rd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_PROFILES_ACTIVE: "docker"

networks:
  coffee_and_happiness_network:
    driver: bridge
